### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by rugk** [vboxme/Portable-VirtualBox#28]
At first the license you want to apply isn't explicitly added in a new text file, which is best practice.

But apart from that in [some files] (https://github.com/vboxme/Portable-VirtualBox/blob/master/source/Portable-VirtualBox.au3#L4) you write that this is licensed under a CC license. However CC licenses [should not be used] (https://wiki.creativecommons.org/FAQ#Can_I_apply_a_Creative_Commons_license_to_software.3F) for software.
I would recommend to [choose another software license] (http://choosealicense.com/) for this purpose.

More information about licenses on Github: https://help.github.com/articles/open-source-licensing/

**Comment by runarbu** [comment]
I totally agree. The CC license is not ideal for software. Unfortunately when this license first has been applied it is very hard to change. To change to another license we would have to get permission from everyone that has participated in the project, and that is not possible because some of them we have lost track of.

I will however add a license text file at least.

**Comment by rugk** [comment]
Well... in the files there it is stated that there is "one author et al.". So AFAIK he could change the license - I think to ask all "et al" isn't necessary.
> ; Author         : Michael Meyer (michaelm_007) et al.
The email address listed there below is a bit useless too...

However of course all previous work [will stay licensed under the CC license] (https://wiki.creativecommons.org/FAQ#What_if_I_change_my_mind_about_using_a_CC_license.3F). Only the new work will be licensed under the new license. So if you want you can ask all current contributors whether and to which license you want to change.

**Comment by Megachip** [comment]
@rugk and he is the one which is "verschollen"

**Comment by runarbu** [comment]
Michael is the original developer. I have tried to reach him many times, but he is nowhere to be found.

At the human readable version of the CC BY-NC-SA 3.0 license ( https://creativecommons.org/licenses/by-nc-sa/3.0/ ) there is a part called **ShareAlike** that sees *"If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original."*

I am not a lawyer, but as I interpret this so will any new code we produce be to *"build upon the material"*, and would therefore also have to be CC BY-NC-SA 3.0 licensed.

**Comment by rugk** [comment]
@runarbu
Yes you're right, so only the original developer could relicense this. And if he's lost then we can't do many things, you're right. Unfortunately...
