### ISSUE TITLE
Problem with French Translation

### ISSUE THREAD

**Issue by Machou** [vboxme/Portable-VirtualBox#38]
Hello

Can you add the support of UTF-8 for french translation ?

Try : https://i.imgur.com/uaX7YKa.png

**Comment by Megachip** [comment]
Which OS did you use? (File is already UTF-8)
https://github.com/vboxme/Portable-VirtualBox/blob/master/data/language/french.ini

**Comment by runarbu** [comment]
I have done some testing with the French and Russian language files on Windows 8 and Windows 10, and the utf character do indeed looks broken

**Windows 10**
French: http://runarb.com/div/pvutf/win10_french.png
Russian: http://runarb.com/div/pvutf/win10_russian.png

**Windows 8**
French: http://runarb.com/div/pvutf/win8_french.png
Russian: http://runarb.com/div/pvutf/win8_russian.png

**Comment by Megachip** [comment]
@runarbu so looks like autoIt did not interpret the encoding of the textiles correctly.

https://www.autoitscript.com/autoit3/docs/intro/unicode.htm

**Comment by runarbu** [comment]
This seems to work if the files get encoded with UTF-16 LE with BOM.

I have looked at the encoding of the other language files also and they are in several different formats: 

catalan.ini : UTF-8 BOM
chinese.ini : GB 2312 (Simplified)
english.ini : UTF-8
french.ini : UTF-8 BOM
german.ini : ANSI
italian.ini : ANSI
japanese.ini : Shift-JIS
polish.ini : ANSI
portuguese.ini : ANSI
russian.ini : Windows-1251
spanish.ini : ANSI
ukrainian.ini : Windows-1251

(formats as reported by Notepad++ )

@Megachip : any suggestion on what to do? Shall we just set the French language file to UTF-16 LE with BOM for now?

**Comment by Machou** [comment]
I'm on Windows 7 =)

**Comment by Megachip** [comment]
@Machou "The recommended script format is UTF-8 with BOM" ... so I think we should not remove it. Also I can't se any differences in my editor. Did you try the language file without the BOM Header? Is language shown correct?

@runarbu we should at least use ONE encoding for all language files. Except Japanese and Chinese, all would work in ANSI. But it didn't feels the right way. 
If I'm right, IniRead (https://github.com/vboxme/Portable-VirtualBox/blob/60c6a36794f51b29ff89ea6eba2142da900b93fa/source/Portable-VirtualBox.au3#L244-L276) did not support UTF-8. 

There are some solutions on google. Did not know, which is the best. But if recoding the file solves the problem, we should use (and test) this first ;)

**Comment by Machou** [comment]
Yes i have try (without BOM & normal) no work ^^

**Comment by p060477** [comment]
hi runar!
so you are still alive!!
why you do not reply about the issues with the network bridge and win 10..??..
pls hit a bit..my canterville ghost..
:(

**Comment by phenri** [comment]
I converted the language file ini from utf to ansi and seem fixed.

**Comment by p060477** [comment]
hi runar a simple question still unanswered by you:
is now portable vb completely suitable with win 10?
i mean is useable the network BRIDGED?
or we are still forced to use only NAT server?
pls reply clearly!
