### ISSUE TITLE
Problem with the download link connection

### ISSUE THREAD

**Issue by richy33** [vboxme/Portable-VirtualBox#42]
Hi ..
I have some problem when a try to download the program by the provide linkin the page .. the conexion is very slow to download.. sometimes the connection is dropped ..
thanks ...

**Comment by runarbu** [comment]
Is it the starter it self you have problem downloading? The link looks like this: http://files.vbox.me/files/Portable-VirtualBox_v5.0.26-Starter_v6.4.10-Win_all.exe

The file is only about 1.5 mb and hosted on a reasonable server, so any download should be fast.

**Comment by p060477** [comment]
hi runar!
but pls reply clearly:
does now the portable vers run without issues on win 10 home?
also the network bridged issue and the full drag n drop are solved?
pls reply thxs!
cheers!
