### ISSUE TITLE
Portable Vboxes totally isolated

### ISSUE THREAD

**Issue by kmdock** [vboxme/Portable-VirtualBox#44]
I had a heck of a time understanding how to view your settings.  I finally found it on an unrelated site.  By default you don't allow USB or Networking for security purposes.  I guess that's true, but it's PITA for me.

Still, your instructions are not easy to understand.  If it hadn't been for the other site, I'd still be frustrated and without networking on either of my guests.

**Comment by kmdock** [comment]
Further info on this.  "network config sample has stopped working"  Portable vbox will not start the network.  Host is Win 10 Home.  "Windows will close the program and notify you if a solution is available."  Windows has nothing to say about it, apparently.  What's going wrong here?

**Comment by Megachip** [comment]
@kmdock see issue #6 , which is imho still unfixed.
