### ISSUE TITLE
Replace outdated 7-Zip 9.20 with non-vulnerable 16.04 [ please label as bug ]

### ISSUE THREAD

**Issue by Rastwood** [vboxme/Portable-VirtualBox#45]
Hello Dev-Team!

Could the next release contain the version 16.04 of 7-zip in Portable-VirtualBox\data\tools, which fixes some serious vulnerabilities?

See https://www.cvedetails.com/vulnerability-list/vendor_id-9220/7-zip.html and http://www.7-zip.org/download.html.

Fixing this security issue would be reasonable and stops vulnerability checker complaints, e.g. from Secunia (old company name) PSI.

Thank you in advance and for your work on this software!

Best Regards

Gerd

**Comment by p060477** [comment]
hi!
but are you able to use the net work option?
is it suitable with win 10?
runar buvik the dev has incredibly disappeared...
so shamely..
:(

**Comment by p060477** [comment]
but is working the network bridged with win 10?

**Comment by p060477** [comment]
or is still the OLD BUG unsolved??
