### ISSUE TITLE
Windows 10 Creators Update: Portable Virtual Box does not start

### ISSUE THREAD

**Issue by viper73** [vboxme/Portable-VirtualBox#46]
After installing the Windows 10 Creators Update (64bit) the Portable Virtual Box (5.0.26) does not start anymore. I already downloaded everything again/new, but it still does not work. Portable virtuar box tries to start, and after a few seconds it shows the "closing virtual box" window. No chance to get it running again. I hope there will be a fix soon so i can work with my virtual box machines again...

**Comment by p060477** [comment]
the only man that could help,mr runar buvik,has shamely -disappeared-..
what a pity...
:(

**Comment by viper73** [comment]
Thats no good news, but thank you to let me know.
Does anybody have the same problem or is that just me with the creators update problem?

**Comment by p060477** [comment]
were you been able to use net work before..?
here is a topic abbandoned by runar..the project manager for portable vbox..what a shane..:
https://github.com/vboxme/Portable-VirtualBox/issues/33#issuecomment-188187465

**Comment by qzcw** [comment]
I have exactly the same issue. After the Creators Update VirtualBox portable doesn't start on any of my computers.

**Comment by p060477** [comment]
RUNAR...where are you...??!!..
shamely disappeared..

**Comment by qzcw** [comment]
I got this working. 

The current VBox portable "loader" is ok, but you must manually download a more recent version of Virtual Box installer from their website (https://www.virtualbox.org/wiki/Downloads). 
I tried version 5.1.22 (latest by today), downloaded the exe (VirtualBox-5.1.22-115126-Win.exe) and let the Portable-VirtualBox installation program to extract it. Then the Portable VirtualBox works with Creators Update just as it has always done before.

**Comment by p060477** [comment]
are you able to use network bridged?

**Comment by qzcw** [comment]
No, I can't select the Bridget Adapter. It complains about "Invalid settings detected".

Actually, I have never used anything else but NAT mode. I need only the internet.

**Comment by p060477** [comment]
this is THE BUG..since win 10...and runar buvik did not anything against this
so THE BUG SHAMELY REMAINS..
what a real pity..

**Comment by Megachip** [comment]
Issue one VB, not on PVB

**Comment by p060477** [comment]
"Issue one VB, not on PVB"...:

..is the EXACT countrary....!!...
issues are on PORTABLE VB...since YEARS
why you don't write CLEARLY on vbox.me site and HERE that PVBOX
is fully compatible only till WIN 7..and really NOT for 
win 8 and WIN 10..??..
it should be helpful to finally CLARIFY
;)
:(

**Comment by 1988fido** [comment]
2020 and still the same issue :/ couldn't even make it work, tried many software and all are using something virtual box so cant do it , "Lili" and the official virtualbox , many of them when it comes to being portable virtual machine not doable and get same error coz all of them uses the same old virtualbox-portable version
