### ISSUE TITLE
Portable VirtualBox doesn't start on Windows 10 Redstone 2

### ISSUE THREAD

**Issue by musti35** [vboxme/Portable-VirtualBox#47]
Hi friends;

I installed "Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all.exe"  on  Windows 10 Redstone2  64bit.

When I started VirtualBoxPortable,  firstly it said "Please start VirtualBox again, so that all paths can be adapted!" 

I clicked OK.

Then a notification appeared on tray "Right click on me..."
And then it immediately closed. 

I can't see virtual box app window.

What can i do?

**Comment by luckebar** [comment]
He also writes to me the same message and does not work, I also win 10, after the last update has stopped running. Please help me

**Comment by Megachip** [comment]
Working fine on Build 16251 with VB 5.1.26. Which version is Redstone 2? Which version of VB did you try?
