### ISSUE TITLE
network BRIDGED and win 10 home 64 

### ISSUE THREAD

**Issue by p060477** [vboxme/Portable-VirtualBox#49]
hi runar a simple question still unanswered by you:
is now portable vb completely suitable with win 10?
i mean is useable the network BRIDGED?
or we are still forced to use only NAT server?
pls reply clearly!

**Comment by Megachip** [comment]
NO, it isn't. Cause noone had the time to fix it. I thin these question was allready answered more than once.
What about fixing by yourself? You put so much energy into asking and annoying. Put them into searching and fixing the problem.

**Comment by p060477** [comment]
hi RUNAR...i see you around here..are you able to FIX this BUG..??!!
