### ISSUE TITLE
vbox.me website dead?

### ISSUE THREAD

**Issue by adnoh** [vboxme/Portable-VirtualBox#51]
Can't open the website anymore? Getting a "server not found"

**Comment by p060477** [comment]
it has been years that we can not use anymore bridged net but only nato..:
vbox portable is dead since years...
hey Runar Buvik are you still here..??!!
:)

**Comment by runarbu** [comment]
@adnoh is it http://www.vbox.me/ you are unable to access? I seems up for me and according to this it should work for everyone else also: http://downforeveryoneorjustme.com/www.vbox.me

@p060477 I am aware of your issue, but have been unable to make bridged networking work. Hijackin everyone else's issues will not help me resolve this any faster.

**Comment by p060477** [comment]
hi runar!
so really glad to ear again from you!
so you really are not definetively dead!
you write.
" resolve this any faster."...:
are you playing fools of all of us..??..-faster-..??
..it has been 2 , TWO, YEARS issue/BUG 
STILL UNSOLVED...
what a pity
what a real SHAME
:(

**Comment by Megachip** [comment]
Everything fine here too.
