### ISSUE TITLE
Update to 5.1.26

### ISSUE THREAD

**Issue by gusbemacbe** [vboxme/Portable-VirtualBox#52]
Hello,

I want to update from 5.1.8 to 5.1.26. Please, update the software.

**Comment by p060477** [comment]
it is simply useless cause since 3 years it is not possible to use network bridged but only NAT..
due to the lack of the presence of its developer..mr Runar Buvick..
what a pity..
what a shame..
:(

**Comment by gusbemacbe** [comment]
Are you speaking of @runarbu? Strange, he made the latest commit in May this year.

**Comment by p060477** [comment]
o yes is very active..except on this very BIG BUG of the impossibility of using the network bridged..
the BUG is still there since 3 years..
what a shame..
:(

**Comment by Megachip** [comment]
duplicate of https://github.com/vboxme/Portable-VirtualBox/issues/53
