### ISSUE TITLE
Portable-VirtualBox does not run on USB drive

### ISSUE THREAD

**Issue by GG2791** [vboxme/Portable-VirtualBox#64]
Downloaded/unzipped Portable-VirtualBox_v5.1.22-Starter_v6.4.10-Win_all to my USB drive (64GB PNY), Portable-VirtualBox will not run after selecting the Language.  Is this known issue?

**Comment by Megachip** [comment]
Nope. Could you explain what exactly not working? What happens or not happens?

**Comment by park-changkyu** [comment]
Although the VirtualBox program itself runs on the USB, an error occurs when attempting to run the Guest OS.
![Error](https://github.com/user-attachments/assets/f1f9bcf7-f6ac-4b80-95a8-499a3f5380cf)
