### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by measlystorm** [vboxme/Portable-VirtualBox#74]
Can i use this on a AMD machine? When I use this normal virtual box and not portable, it wont load up for myself... Could you let me know please. Thanks

**Comment by Megachip** [comment]
Both, portable and normal should work on all x86 and x86_64 architectures

**Comment by tech3869** [comment]
FIX: supr3hardenedwinrespawn VirtualBox error

Install driver VBoxDrV.inf
https://windowsreport.com/virtualbox-error-supr3hardenedwinrespawn/

**Comment by tech3869** [comment]
VirtualBox Errors Hub
https://windowsreport.com/tag/virtual-box-errors/
