### ISSUE TITLE
Portable-VirtualBox does not run on USB drive

### ISSUE THREAD

**Issue by park-changkyu** [vboxme/Portable-VirtualBox#94]
Although the VirtualBox program itself runs on the USB, an error occurs when attempting to run the Guest OS.

![Error](https://github.com/user-attachments/assets/c4351f46-caf3-4e6e-bb6a-e2b9ad615d58)

**Comment by Deac2** [comment]
Try this version https://github.com/Deac2/Portable-VirtualBox/archive/refs/heads/master.zip
You have a strange error, it started under winpe, but the launch of the machines themselves did not work, replaced all %CD% with @ScriptDir

**Comment by enzogtb** [comment]
try to go to [your virtualbox installation path]\\App\x64\drivers\vboxsup and right click on VBoxSup.inf and "install"
